# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_config_fmask.ui'
#
# Created: Wed May 14 22:02:09 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_config_fmask(object):
    def setupUi(self, config_fmask):
        config_fmask.setObjectName(_fromUtf8("config_fmask"))
        config_fmask.resize(700, 550)
        self.gridLayout = QtGui.QGridLayout(config_fmask)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.line = QtGui.QFrame(config_fmask)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 0, 1, 1, 1)
        self.widget_MTL = QtGui.QWidget(config_fmask)
        self.widget_MTL.setObjectName(_fromUtf8("widget_MTL"))
        self.gridLayout_2 = QtGui.QGridLayout(self.widget_MTL)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.button_save = QtGui.QPushButton(self.widget_MTL)
        self.button_save.setMaximumSize(QtCore.QSize(75, 16777215))
        self.button_save.setObjectName(_fromUtf8("button_save"))
        self.gridLayout_2.addWidget(self.button_save, 7, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.widget_MTL)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 5, 0, 1, 1)
        self.edit_MTL = QtGui.QLineEdit(self.widget_MTL)
        self.edit_MTL.setObjectName(_fromUtf8("edit_MTL"))
        self.gridLayout_2.addWidget(self.edit_MTL, 2, 0, 1, 1)
        self.button_MTL = QtGui.QPushButton(self.widget_MTL)
        self.button_MTL.setMaximumSize(QtCore.QSize(75, 16777215))
        self.button_MTL.setObjectName(_fromUtf8("button_MTL"))
        self.gridLayout_2.addWidget(self.button_MTL, 2, 1, 1, 1)
        self.table_MTL = QtGui.QTableWidget(self.widget_MTL)
        self.table_MTL.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.table_MTL.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.table_MTL.setAlternatingRowColors(True)
        self.table_MTL.setColumnCount(2)
        self.table_MTL.setObjectName(_fromUtf8("table_MTL"))
        self.table_MTL.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.table_MTL.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table_MTL.setHorizontalHeaderItem(1, item)
        self.table_MTL.horizontalHeader().setStretchLastSection(True)
        self.table_MTL.verticalHeader().setStretchLastSection(False)
        self.gridLayout_2.addWidget(self.table_MTL, 4, 0, 1, 2)
        self.label_2 = QtGui.QLabel(self.widget_MTL)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 3, 0, 1, 2)
        self.label = QtGui.QLabel(self.widget_MTL)
        self.label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 2)
        self.edit_save = QtGui.QLineEdit(self.widget_MTL)
        self.edit_save.setObjectName(_fromUtf8("edit_save"))
        self.gridLayout_2.addWidget(self.edit_save, 7, 0, 1, 1)
        self.cbox_formats = QtGui.QComboBox(self.widget_MTL)
        self.cbox_formats.setObjectName(_fromUtf8("cbox_formats"))
        self.gridLayout_2.addWidget(self.cbox_formats, 9, 0, 1, 2)
        self.label_7 = QtGui.QLabel(self.widget_MTL)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 8, 0, 1, 2)
        self.label_8 = QtGui.QLabel(self.widget_MTL)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 6, 0, 1, 2)
        self.gridLayout.addWidget(self.widget_MTL, 0, 0, 1, 1)
        self.widget_config = QtGui.QWidget(config_fmask)
        self.widget_config.setMinimumSize(QtCore.QSize(300, 0))
        self.widget_config.setObjectName(_fromUtf8("widget_config"))
        self.gridLayout_3 = QtGui.QGridLayout(self.widget_config)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.line_2 = QtGui.QFrame(self.widget_config)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_3.addWidget(self.line_2, 9, 0, 1, 2)
        self.cbox_water = QtGui.QCheckBox(self.widget_config)
        self.cbox_water.setObjectName(_fromUtf8("cbox_water"))
        self.gridLayout_3.addWidget(self.cbox_water, 13, 0, 1, 1)
        self.lab_fmaskconfig = QtGui.QLabel(self.widget_config)
        self.lab_fmaskconfig.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lab_fmaskconfig.setObjectName(_fromUtf8("lab_fmaskconfig"))
        self.gridLayout_3.addWidget(self.lab_fmaskconfig, 0, 0, 1, 2)
        self.lab_shadow_buffer = QtGui.QLabel(self.widget_config)
        self.lab_shadow_buffer.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lab_shadow_buffer.setObjectName(_fromUtf8("lab_shadow_buffer"))
        self.gridLayout_3.addWidget(self.lab_shadow_buffer, 5, 0, 1, 2)
        self.slider_cloud_prob = QtGui.QSlider(self.widget_config)
        self.slider_cloud_prob.setMinimum(-500)
        self.slider_cloud_prob.setMaximum(1000)
        self.slider_cloud_prob.setProperty("value", 225)
        self.slider_cloud_prob.setOrientation(QtCore.Qt.Horizontal)
        self.slider_cloud_prob.setTickPosition(QtGui.QSlider.TicksBelow)
        self.slider_cloud_prob.setTickInterval(100)
        self.slider_cloud_prob.setObjectName(_fromUtf8("slider_cloud_prob"))
        self.gridLayout_3.addWidget(self.slider_cloud_prob, 2, 0, 1, 2)
        self.button_sym_snow = QtGui.QPushButton(self.widget_config)
        self.button_sym_snow.setObjectName(_fromUtf8("button_sym_snow"))
        self.gridLayout_3.addWidget(self.button_sym_snow, 16, 1, 1, 1)
        self.cbox_land = QtGui.QCheckBox(self.widget_config)
        self.cbox_land.setObjectName(_fromUtf8("cbox_land"))
        self.gridLayout_3.addWidget(self.cbox_land, 11, 0, 1, 1)
        self.spin_shadow_buffer = QtGui.QSpinBox(self.widget_config)
        self.spin_shadow_buffer.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spin_shadow_buffer.setMaximum(1000)
        self.spin_shadow_buffer.setObjectName(_fromUtf8("spin_shadow_buffer"))
        self.gridLayout_3.addWidget(self.spin_shadow_buffer, 6, 0, 1, 2)
        self.label_5 = QtGui.QLabel(self.widget_config)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 10, 0, 1, 2)
        self.cbox_shadow = QtGui.QCheckBox(self.widget_config)
        self.cbox_shadow.setChecked(True)
        self.cbox_shadow.setObjectName(_fromUtf8("cbox_shadow"))
        self.gridLayout_3.addWidget(self.cbox_shadow, 15, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.widget_config)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 3, 0, 1, 2)
        self.button_sym_shadow = QtGui.QPushButton(self.widget_config)
        self.button_sym_shadow.setObjectName(_fromUtf8("button_sym_shadow"))
        self.gridLayout_3.addWidget(self.button_sym_shadow, 15, 1, 1, 1)
        self.button_sym_water = QtGui.QPushButton(self.widget_config)
        self.button_sym_water.setObjectName(_fromUtf8("button_sym_water"))
        self.gridLayout_3.addWidget(self.button_sym_water, 13, 1, 1, 1)
        self.cbox_cloud = QtGui.QCheckBox(self.widget_config)
        self.cbox_cloud.setChecked(True)
        self.cbox_cloud.setObjectName(_fromUtf8("cbox_cloud"))
        self.gridLayout_3.addWidget(self.cbox_cloud, 17, 0, 1, 1)
        self.lab_cloud_prob_val = QtGui.QLabel(self.widget_config)
        self.lab_cloud_prob_val.setText(_fromUtf8(""))
        self.lab_cloud_prob_val.setObjectName(_fromUtf8("lab_cloud_prob_val"))
        self.gridLayout_3.addWidget(self.lab_cloud_prob_val, 1, 1, 1, 1)
        self.spinBox = QtGui.QSpinBox(self.widget_config)
        self.spinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox.setMaximum(10000)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.gridLayout_3.addWidget(self.spinBox, 8, 0, 1, 2)
        self.button_sym_cloud = QtGui.QPushButton(self.widget_config)
        self.button_sym_cloud.setObjectName(_fromUtf8("button_sym_cloud"))
        self.gridLayout_3.addWidget(self.button_sym_cloud, 17, 1, 1, 1)
        self.cbox_snow = QtGui.QCheckBox(self.widget_config)
        self.cbox_snow.setChecked(True)
        self.cbox_snow.setObjectName(_fromUtf8("cbox_snow"))
        self.gridLayout_3.addWidget(self.cbox_snow, 16, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.widget_config)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 7, 0, 1, 2)
        self.lab_cloud_prob = QtGui.QLabel(self.widget_config)
        self.lab_cloud_prob.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lab_cloud_prob.setObjectName(_fromUtf8("lab_cloud_prob"))
        self.gridLayout_3.addWidget(self.lab_cloud_prob, 1, 0, 1, 1)
        self.spin_cloud_buffer = QtGui.QSpinBox(self.widget_config)
        self.spin_cloud_buffer.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spin_cloud_buffer.setMaximum(1000)
        self.spin_cloud_buffer.setObjectName(_fromUtf8("spin_cloud_buffer"))
        self.gridLayout_3.addWidget(self.spin_cloud_buffer, 4, 0, 1, 2)
        self.button_sym_land = QtGui.QPushButton(self.widget_config)
        self.button_sym_land.setObjectName(_fromUtf8("button_sym_land"))
        self.gridLayout_3.addWidget(self.button_sym_land, 11, 1, 1, 1)
        self.gridLayout.addWidget(self.widget_config, 0, 2, 1, 1)
        self.button_box = QtGui.QDialogButtonBox(config_fmask)
        self.button_box.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Help|QtGui.QDialogButtonBox.RestoreDefaults|QtGui.QDialogButtonBox.Save)
        self.button_box.setCenterButtons(False)
        self.button_box.setObjectName(_fromUtf8("button_box"))
        self.gridLayout.addWidget(self.button_box, 1, 0, 1, 4)

        self.retranslateUi(config_fmask)
        QtCore.QObject.connect(self.button_box, QtCore.SIGNAL(_fromUtf8("accepted()")), config_fmask.accept)
        QtCore.QObject.connect(self.button_box, QtCore.SIGNAL(_fromUtf8("rejected()")), config_fmask.reject)
        QtCore.QMetaObject.connectSlotsByName(config_fmask)

    def retranslateUi(self, config_fmask):
        config_fmask.setWindowTitle(_translate("config_fmask", "Dialog", None))
        self.button_save.setText(_translate("config_fmask", "Open", None))
        self.label_6.setText(_translate("config_fmask", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Output Options:</span></p></body></html>", None))
        self.button_MTL.setText(_translate("config_fmask", "Open", None))
        self.table_MTL.setSortingEnabled(True)
        item = self.table_MTL.horizontalHeaderItem(0)
        item.setText(_translate("config_fmask", "Metadata Key", None))
        item = self.table_MTL.horizontalHeaderItem(1)
        item.setText(_translate("config_fmask", "Value", None))
        self.label_2.setText(_translate("config_fmask", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Metadata</span></p></body></html>", None))
        self.label.setText(_translate("config_fmask", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Landsat Metadata File (MTL)</span></p></body></html>", None))
        self.label_7.setText(_translate("config_fmask", "Format:", None))
        self.label_8.setText(_translate("config_fmask", "Filename:", None))
        self.cbox_water.setText(_translate("config_fmask", "Clear water", None))
        self.lab_fmaskconfig.setText(_translate("config_fmask", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Fmask Configuration:</span></p></body></html>", None))
        self.lab_shadow_buffer.setText(_translate("config_fmask", "Shadow Buffer:", None))
        self.button_sym_snow.setText(_translate("config_fmask", "Color", None))
        self.cbox_land.setText(_translate("config_fmask", "Clear land", None))
        self.label_5.setText(_translate("config_fmask", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Fmask Symbology:</span></p></body></html>", None))
        self.cbox_shadow.setText(_translate("config_fmask", "Shadow", None))
        self.label_3.setText(_translate("config_fmask", "Cloud buffer:", None))
        self.button_sym_shadow.setText(_translate("config_fmask", "Color", None))
        self.button_sym_water.setText(_translate("config_fmask", "Color", None))
        self.cbox_cloud.setText(_translate("config_fmask", "Cloud", None))
        self.button_sym_cloud.setText(_translate("config_fmask", "Color", None))
        self.cbox_snow.setText(_translate("config_fmask", "Snow", None))
        self.label_4.setText(_translate("config_fmask", "Snow Buffer:", None))
        self.lab_cloud_prob.setText(_translate("config_fmask", "Cloud probability:", None))
        self.button_sym_land.setText(_translate("config_fmask", "Color", None))

